### ISSUE TITLE
 No module named 'marching_cubes'

### ISSUE THREAD

**Issue by wamwam00** [huangjh-pub/di-fusion#1]
Hello,when I run  python main.py configs/fusion-lr-kt.yaml --vis 1
I get the result 
Using C:\Users\huangzhizhou\AppData\Local\torch_extensions\torch_extensions\Cache as PyTorch extensions root...
C:\Program Files\Python37\lib\site-packages\torch\utils\cpp_extension.py:274: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
Detected CUDA files, patching ldflags
Emitting ninja build file C:\Users\huangzhizhou\AppData\Local\torch_extensions\torch_extensions\Cache\marching_cubes\build.ninja...
Building extension module marching_cubes...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.0
Loading extension module marching_cubes...
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from system import map
  File "H:\MeshReconstruction\di-fusion\system\map.py", line 13, in <module>
    import system.ext
  File "H:\MeshReconstruction\di-fusion\system\ext\__init__.py", line 16, in <module>
    verbose=__COMPILE_VERBOSE)
  File "C:\Program Files\Python37\lib\site-packages\torch\utils\cpp_extension.py", line 980, in load
    keep_intermediates=keep_intermediates)
  File "C:\Program Files\Python37\lib\site-packages\torch\utils\cpp_extension.py", line 1196, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "C:\Program Files\Python37\lib\site-packages\torch\utils\cpp_extension.py", line 1543, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "C:\Program Files\Python37\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'marching_cubes'

**Comment by heiwang1997** [comment]
Hi @wamwam00, from the error message I am wondering if your c++ compiler is working correctly...
I haven't tested this code on Windows yet - could you please test it on Ubuntu?

**Comment by huangjh-pub** [comment]
The issue seems to be stale because there's no activity for a month. Feel free to reopen if you are still having problems.

**Comment by LiuXinqi12** [comment]
Hi, i meet the same problem, have you sovle it ? i run it in ubuntu 16. How pytorch version your used?

**Comment by zwq1111** [comment]
I meet the problem when I run the code : ModuleNotFoundError: No module named 'marching_cubes'
Could you help me solve it？
