### ISSUE TITLE
RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered

### ISSUE THREAD

**Issue by hanfeng-wu** [huangjh-pub/di-fusion#7]
When I start tracking, the first depth map can be projected, when I press ',' again, the compiler gives me this:

```
INFO - 2022-05-10 14:18:10,560 - map - Map size Nx = 80, Ny = 40, Nz = 80
INFO - 2022-05-10 14:18:12,698 - main - Frame ID = 0
/home/wuha/anaconda3/envs/autosdf/lib/python3.8/site-packages/torch/nn/functional.py:3609: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
/home/wuha/anaconda3/envs/autosdf/lib/python3.8/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448278899/work/aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
INFO - 2022-05-10 14:18:13,219 - map - 3468 voxels will be updated by the encoder. Points/Voxel: avg = 71.76152801513672, min = 1.0, max = 183.0
INFO - 2022-05-10 14:18:14,416 - main - Frame ID = 1
Traceback (most recent call last):
  File "main.py", line 147, in <module>
    engine.run()
  File "main.py", line 71, in refresh
    frame_pose = vis_param.tracker.track_camera(frame_data.rgb, frame_data.depth, frame_data.calib,
  File "/home/wuha/Hanfeng/TUM/MasterSeminar/di-fusion/system/tracker.py", line 124, in track_camera
    final_pose = self.gauss_newton(self.all_pd_pose[-1].dot(lspeed), cur_intensity, cur_depth, cur_dIdxy, pc_data, calib)
  File "/home/wuha/Hanfeng/TUM/MasterSeminar/di-fusion/system/tracker.py", line 240, in gauss_newton
    sdf_H, sdf_g, sdf_energy = self.compute_sdf_Hg(i_iter, last_pose, cur_delta_pose, obs_xyz, i_iter == -1)
  File "/home/wuha/Hanfeng/TUM/MasterSeminar/di-fusion/system/tracker.py", line 191, in compute_sdf_Hg
    dsdf_dpos = torch.autograd.grad(cur_obs_sdf, [cur_obs_xyz], grad_outputs=torch.ones_like(cur_obs_sdf),
  File "/home/wuha/anaconda3/envs/autosdf/lib/python3.8/site-packages/torch/autograd/__init__.py", line 226, in grad
    return Variable._execution_engine.run_backward(
RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
```
Do you have encountered the same Problem? My cuda version is 11.6

**Comment by huangjh-pub** [comment]
Hi Hanfeng, 

As we've discussed in the email, I believe that adding the following line:
```python
extra_cuda_cflags=['-Xcompiler -fno-gnu-unique']
```
to all the 'load' function in `system/ext/__init__.py` may have solved your problem.

Feel free to leave further questions here :)

Best.

**Comment by hanfeng-wu** [comment]
Thank you very much, it did work!
