### ISSUE TITLE
Compilation failed when first run main.py

### ISSUE THREAD

**Issue by LongruiDong** [huangjh-pub/di-fusion#8]
Hi ~
Thanks for sharing this great work.

when I run 
```
python main.py configs/fusion-lr-kt.yaml --vis 1
```

the compilation of marching_cube failed: (following output log with __COMPILE_VERBOSE = True)

```
Using /home/dlr/.cache/torch_extensions/py37_cu113 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/dlr/.cache/torch_extensions/py37_cu113/marching_cubes/build.ninja...
Building extension module marching_cubes...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] :/usr/local/cuda:/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=marching_cubes -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1013\" -isystem /home/dlr/anaconda3/envs/di-fusion/lib/python3.7/site-packages/torch/include -isystem /home/dlr/anaconda3/envs/di-fusion/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/dlr/anaconda3/envs/di-fusion/lib/python3.7/site-packages/torch/include/TH -isystem /home/dlr/anaconda3/envs/di-fusion/lib/python3.7/site-packages/torch/include/THC -isystem :/usr/local/cuda:/usr/local/cuda/include -isystem /home/dlr/anaconda3/envs/di-fusion/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /home/dlr/Project/di-fusion/pytorch/system/ext/marching_cubes/mc_interp_kernel.cu -o mc_interp_kernel.cuda.o 
FAILED: mc_interp_kernel.cuda.o 
:/usr/local/cuda:/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=marching_cubes -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1013\" -isystem /home/dlr/anaconda3/envs/di-fusion/lib/python3.7/site-packages/torch/include -isystem /home/dlr/anaconda3/envs/di-fusion/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/dlr/anaconda3/envs/di-fusion/lib/python3.7/site-packages/torch/include/TH -isystem /home/dlr/anaconda3/envs/di-fusion/lib/python3.7/site-packages/torch/include/THC -isystem :/usr/local/cuda:/usr/local/cuda/include -isystem /home/dlr/anaconda3/envs/di-fusion/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /home/dlr/Project/di-fusion/pytorch/system/ext/marching_cubes/mc_interp_kernel.cu -o mc_interp_kernel.cuda.o 
/bin/sh: 1: :/usr/local/cuda:/usr/local/cuda/bin/nvcc: not found
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/dlr/anaconda3/envs/di-fusion/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1814, in _run_ninja_build
    env=env)
  File "/home/dlr/anaconda3/envs/di-fusion/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from system import map
  File "/home/dlr/Project/di-fusion/pytorch/system/map.py", line 13, in <module>
    import system.ext
  File "/home/dlr/Project/di-fusion/pytorch/system/ext/__init__.py", line 19, in <module>
    verbose=__COMPILE_VERBOSE, **optimize_flags)
  File "/home/dlr/anaconda3/envs/di-fusion/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1214, in load
    keep_intermediates=keep_intermediates)
  File "/home/dlr/anaconda3/envs/di-fusion/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1435, in _jit_compile
    is_standalone=is_standalone)
  File "/home/dlr/anaconda3/envs/di-fusion/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1540, in _write_ninja_file_and_build_library
    error_prefix=f"Error building extension '{name}'")
  File "/home/dlr/anaconda3/envs/di-fusion/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1824, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'marching_cubes'
```

I indeed have nvcc in my ubuntu 20.04:

```
(di-fusion) d@pc:~/Project/di-fusion/pytorch$ which nvcc
/usr/local/cuda/bin/nvcc
(di-fusion) d@pc:~/Project/di-fusion/pytorch$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0

```

do you know how to solve it?

**Comment by heiwang1997** [comment]
Please kindly check your `$CUDA_HOME` environment variable, which should be `/usr/local/cuda`.

**Comment by LongruiDong** [comment]
> Please kindly check your `$CUDA_HOME` environment variable, which should be `/usr/local/cuda`.

yeah! I got it's path wrong， after I change to above right cuda path, there is no error.
however, compilation seems to be stuck and never runs,
I ctrl +C, get:

```
(di-fusion) dlr@pc:~/Project/di-fusion/pytorch$ python main.py configs/fusion-lr-kt.yaml
Using /home/dlr/.cache/torch_extensions/py37_cu113 as PyTorch extensions root...
^CTraceback (most recent call last):
  File "main.py", line 11, in <module>
    from system import map
  File "/home/dlr/Project/di-fusion/pytorch/system/map.py", line 13, in <module>
    import system.ext
  File "/home/dlr/Project/di-fusion/pytorch/system/ext/__init__.py", line 19, in <module>
    verbose=__COMPILE_VERBOSE, **optimize_flags)
  File "/home/dlr/anaconda3/envs/di-fusion/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1214, in load
    keep_intermediates=keep_intermediates)
  File "/home/dlr/anaconda3/envs/di-fusion/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1439, in _jit_compile
    baton.wait()
  File "/home/dlr/anaconda3/envs/di-fusion/lib/python3.7/site-packages/torch/utils/file_baton.py", line 42, in wait
    time.sleep(self.wait_seconds)
KeyboardInterrupt


```

**Comment by LongruiDong** [comment]
Oh I found the reason : 
[ref1](https://github.com/zhou13/neurvps/issues/1)， [ref2](https://blog.csdn.net/qq_38677322/article/details/109696077)

Thank you~i🤣
